### ISSUE TITLE
Tournaments :: Bonuses :: Add Bonus

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#12]
Required:
* Modal

**Comment by VC-WhitchurchA** [comment]
Implemented Modal and returned functions for current available bonuses

TODO:
- Series Bonuses
- Average Based Bonuses
- Age Based Bonuses
- Divisional Based Bonuses
- Round Based Bonuses

**Comment by VC-WhitchurchA** [comment]
Closing this and creating separate tickets for outstanding bonus types
