### ISSUE TITLE
Tournaments :: Entries :: Entry Forms

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#28]
**TODO**
- [x] Settings
- [x] Rules
- [ ] Print
- [x] Fees
- [x] Deposits

**Comment by VC-WhitchurchA** [comment]
Implementation in progress:

![image](https://user-images.githubusercontent.com/35663319/38174884-1149ce86-35cc-11e8-8047-6c8273348bcb.png)

**Comment by davcpas1234** [comment]
Removing Print as a task for this ticket and raising a non-priority to close this down.
