### ISSUE TITLE
Tournaments :: Home :: Remove Entry Dashboard Hero

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#31]

**Comment by VC-WhitchurchA** [comment]
Maybe we could replace this with a card implementation?
![image](https://user-images.githubusercontent.com/35663319/35650921-b97ed5e0-06d5-11e8-9430-4de3a621fd68.png)

**Comment by davcpas1234** [comment]
I have removed this currently. I will add that idea to the pool @VC-WhitchurchA
