### ISSUE TITLE
Tournaments :: Entries :: Inbound :: Asset Button

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#43]
Create asset button to display "Enter via. **bowl**track" or similar

**Comment by VC-WhitchurchA** [comment]
![enter_w_bt_btn](https://user-images.githubusercontent.com/35663319/35651406-8302f936-06d7-11e8-94cb-7c49578db2fb.png)

Something like this?

**Comment by davcpas1234** [comment]
That will definitely work.

**Comment by VC-WhitchurchA** [comment]
Updated asset:
![enter_w_bt_btn](https://user-images.githubusercontent.com/35663319/36006419-bcd7bc24-0d34-11e8-883f-51f929009335.png)
