### ISSUE TITLE
Tournaments :: Home :: New Layout

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#48]
See @VC-WhitchurchA's suggestion in #31

**Comment by VC-WhitchurchA** [comment]
Potential card impl:

![image](https://user-images.githubusercontent.com/35663319/35650921-b97ed5e0-06d5-11e8-9430-4de3a621fd68.png)

**Comment by davcpas1234** [comment]
After a quick thought shower. We could re-layout the home page to the following:

- Tournament Quick Facts
    - High Game of Tournament
    - Combined Tournament Average
    - Total Games Played
- Current Finals (if has rounds & has active finals)
- Current Rounds (if has rounds)
- Current Squads
- Upcoming Squads
- Entry Summary (Cards) as above
    - Total
    - Pending
    - This Week's Entries
    - Today's Entries
- Latest Entries (5)

**Comment by VC-WhitchurchA** [comment]
Implemented in Alpha only, testing and feedback will be needed
