### ISSUE TITLE
Tournaments :: Entries :: Inbound :: Share Link

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#49]
Direct link to share entry link using assets in #43

**Comment by VC-WhitchurchA** [comment]
Links can be passed to the new results sub-domain

**Comment by VC-WhitchurchA** [comment]
My mistake the link above was for results not registration.

This can be access through the registration sub-domain `register.`

**Comment by VC-WhitchurchA** [comment]
Domain is now active and SSL secured

Direct Links can go though:
`https://register.bowl-track.co.uk/tournaments/register/?tournament=TOURNAMENT_IDENT`
