### ISSUE TITLE
Singles Tournaments :: Entries :: Admin :: Team Entry Conventions

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#50]
If a tournament is defined as a Singles event, change to no longer require team name/nationality input and auto-populate from the player 1 details.

For example:
Player 1 Name: David Passmore
Player 1 Nationality: England

Populate these into Team Name and Nationality vs. requiring these to be entered separately

**Comment by VC-WhitchurchA** [comment]
Fixed #50
