### ISSUE TITLE
Tournaments :: Results :: Squad Result Grid

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#52]
**Issues**
Main issues are caused by round integration as this scoring method should not be available once a specific squad's rounds are progressed (or are non-active)

- [x] Squad Grid presents squads even when "progressed"
- [x] Squad Grid is displayed when no active rounds

**Comment by davcpas1234** [comment]
I will link this issue into #53, when resolved it will allow for an easy logic check

**Comment by davcpas1234** [comment]
Resolved no active round display issue with #33's fix.
Will continue to investigate fixes to other issues with #53's implementation

**Comment by davcpas1234** [comment]
Removed all non-active rounds from displaying in the squad grid. I have opened a new issue concerning if a tournament is not round enabled.
