### ISSUE TITLE
Tournaments :: Squads :: Create Status Flow

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#53]
Create Statuses for Squad Creation and Flow:
- Overflow (Closed Pending Requirement)
- Upcoming (Closed)
- Registration Open (Open for Entries)
- Registration Closed (Closed for Entries)
- Check-In (Open for Sign-in)
- Open/In-Progress
- Complete

**Comment by davcpas1234** [comment]
**TODO:**
* Separate squads into:
    * Upcoming
    * Reg & Check-in
    * In-Progress
    * Completed

**Comment by VC-WhitchurchA** [comment]
This has been successfully implemented into the database.

UI & Logic are upcoming

**Comment by VC-WhitchurchA** [comment]
Limited UI & Logic are now in testing

**Comment by VC-WhitchurchA** [comment]
Looking into task based implementation to allow for #44

**Comment by davcpas1234** [comment]
Implemented, moving to monitoring only
