### ISSUE TITLE
Tournaments :: Results :: Match Bonus Issue

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#55]
Capped bonus scoring is not reflected correctly:

**Example**
Using the following bonus setup:
![image](https://user-images.githubusercontent.com/3764587/35766795-6e663686-08d6-11e8-8dab-147b91adf9a2.png)

This should limit score to 300, however this is not reflected in match scoring:
![image](https://user-images.githubusercontent.com/3764587/35766789-4c79f3be-08d6-11e8-883b-8f42a109f796.png)

**Comment by davcpas1234** [comment]
Added server-side functions to allow for client-side calculation and validation of bonus values and max results.

**Comment by davcpas1234** [comment]
Issue is still mirrored in display view:

![image](https://user-images.githubusercontent.com/3764587/35767102-757b28bc-08dd-11e8-8d29-2c67f4860089.png)

**Comment by VC-WhitchurchA** [comment]
This appears to be a server-side limitation currently, I will investigate

**Comment by VC-WhitchurchA** [comment]
Thinking about it logically, a score should never be limited to under 300, @davcpas1234?

**Comment by davcpas1234** [comment]
You're right, so we should put a rule in to not allow a limit below 300. A bonus is the only way to score over 300. As we already have validation on scratch values.

That way we can add the max results up for a team perspective and limit if over.

**Comment by davcpas1234** [comment]
Fixed #55
