### ISSUE TITLE
Tournaments :: Entries :: Re-Entry Only Rounds

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#60]
Some rounds are designed to be offered only to those who have already entered into a tournament. This feature needs to be added.

**Comment by davcpas1234** [comment]
Would this not be re-entry only rounds?

**Comment by VC-WhitchurchA** [comment]
Yes you are right.

**Comment by davcpas1234** [comment]
~Blocked by #54~

**Comment by davcpas1234** [comment]
Logic and UI elements updated.

This will be added to the parent change request for the registration portal to coincide with the user registration changes to allow for entry management etc.
