### ISSUE TITLE
Registration Portal :: UI :: Padding Issue on Mobile

### ISSUE THREAD

**Issue by davcpas1234** [VersCreativeUK/BowlTrack#78]
![20180601_112129](https://user-images.githubusercontent.com/3764587/40836316-2e210712-658e-11e8-9b79-40756fc49104.jpg)

This could be an issue with viewport or padding of the button.

Registration opens @ 8pM tonight (1st June) as a result I am placing this as a P1

**Comment by VC-WhitchurchA** [comment]
Moving to a P2 as this is not UI blocking. However have assigned to DEV-SERV-OPS in BA

**Comment by davcpas1234** [comment]
Resolved
