### ISSUE TITLE
Registration Portal :: Flexbox Issues on IE11

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#79]
Numerous issues have been identified whereby a user cannot complete a full journey through the Registration Portal. (Example Below)

![image](https://user-images.githubusercontent.com/35663319/40988867-164c7636-68e4-11e8-98f9-ac4de99312db.png)

This is caused by known issue with IE11's support of flexbox. The issues are focused around `.shadow-content-block` and `.shadow-content-card`

**Recommendation:** Users should be advised to use Chrome, Firefox or Edge
>**Note:** Edge is now the only "officially" supported browser in the Microsoft portfolio.

**Comment by davcpas1234** [comment]
Could we look into the below. It appears there may be a potential solution we can draw on. Please see below image:

![image](https://user-images.githubusercontent.com/3764587/41064737-5d3e0f32-69d4-11e8-9cba-ad6165f5bf9d.png)

The top payment selection box is done with the workaround, however the bottom is using base code with no CSS intervention.

**Screengrab is from IE11**

**Comment by VC-WhitchurchA** [comment]
Thank you to @davcpas1234 this issue has now been resolved. Workarounds have been removed and fix implemented cross platform
