### ISSUE TITLE
Tournaments :: Rounds :: Links

### ISSUE THREAD

**Issue by VC-WhitchurchA** [VersCreativeUK/BowlTrack#86]
Currently there is a potential issue where "a" team may be "duplicated" when progressing to the "next" round. 

**For Example:**
- Qualifying Round (top 6 qualify)
- High Game Qualifies
- Desperado Round (Winner qualifies)

Result:
- Finishes 6th in main qualifying
- Has round high game

> **Both results would qualify this team to proceed** which is incorrect

**Changes Required:**
- [x] Add database "priority" column to dictate order of progression
- [x] Add filter to remove team identifiers which are already progressing from subsequent link criteria

---

**Additional Changes:**
- [x] Add auto populated priority column to "Create Round" flow
- [x] Add drag and drop order functionality to "Edit Round Links" flow to mimic priority order

**Comment by VC-WhitchurchA** [comment]
Moving this to non-urgent as all "scope" issues are implemented for testing.

**Comment by davcpas1234** [comment]
Implemented
